### PR TITLE
Add post for v0.15.2 release.

### PR DESCRIPTION
**Pull request by ni4**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Something like this has to be done:

https://github.com/metanorma/metanorma.org/blob/050a7efc0e1759fadcc34f000d63fa0ff7f790fb/_specs/metanorma-model-itu.adoc

The problem occurs as the jekyll open project plugin now expects the git repo to be "main" instead of "master". We have to add an attribute to force it to use "master" as in the above file.

**Comment by ni4** [comment]
@ronaldtse Done. Do we really need link to rnp-tools (and repository itself) at all? It was never updated since 2017 and doesn't seem to be helpful at all.

**Comment by ronaldtse** [comment]
We can remove the rnp-tools repo page, sure.

**Comment by ronaldtse** [comment]
Let's merge this first.

**Pull request merged**
